[project]
name = "jbcs2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=3.2.0",
    "hydra-core>=1.3.2",
    "torch>=2.6.0",
    "transformers>=4.48.2",
]
