defaults:
  - _self_
  - experiments: api_models_llm/C1

cache_dir: "/media/data/tmp"

dataset:
  name: "kamel-usp/aes_enem_dataset"
  split: "JBCS2025"

training_params:
  seed: 42
  num_train_epochs: 20
  logging_steps: 100
  metric_for_best_model: "QWK"
  bf16: True

post_training_results:
  model_path: /workspace/jbcs2025-mCorretor/outputs/2025-03-23/23-16-55
