defaults:
  - _self_
  - experiments: api_models_llm/C5

cache_dir: "/media/data/tmp/"

dataset:
  name: "kamel-usp/aes_enem_dataset"
  split: "JBCS2025"

training_params:
  seed: 42
  num_train_epochs: 20
  logging_steps: 100
  metric_for_best_model: "QWK"
  bf16: True

inference:
  model_id: "kamel-usp/jbcs2025_your_model_name"
  seed: 42
  batch_size: 16

post_training_results:
  model_path: /workspace/jbcs2025/outputs/2025-03-24/20-42-59
