defaults:
  - experiments: mbert/C1

cache_dir: "C:\\temp"

dataset:
  name: "kamel-usp/aes_enem_dataset"
  split: "JBCS2025"

training_params:
  train_batch_size: 16
  eval_batch_size: 16
  learning_rate: 2e-5
  num_train_epochs: 3
  weight_decay: 0.01
