model_push:
  model_path: /workspace/jbcs2025/outputs/2025-07-12/Tucano-2b4-Instruct-tucano_classification_lora-C5-full_context-r16
  organization: kamel-usp
  collection:
    name: JBCS2025
    slug: kamel-usp/jbcs2025-67d5e73a4b89c1f0c878159c
