model_push:
  model_path: /workspace/jbcs2025/outputs/2025-07-06/phi-4-phi4_classification_lora-C5-full_context-r16
  organization: kamel-usp
  collection:
    name: JBCS2025
    slug: kamel-usp/jbcs2025-67d5e73a4b89c1f0c878159c
