# Configuration for running inference experiments sequentially
# Use this with --mode inference or --mode train

stop_on_failure: false
delay_between_experiments: 0

experiments:
  # Example: Run experiments with different models for each grade
  - name: "phi35_models_essay_only/C1"
    reference: "phi35_models_essay_only/C1"
  - name: "phi35_models_essay_only/C2"
    reference: "phi35_models_essay_only/C2"
  - name: "phi35_models_essay_only/C3"
    reference: "phi35_models_essay_only/C3"
  - name: "phi35_models_essay_only/C4"
    reference: "phi35_models_essay_only/C4"
  - name: "phi35_models_essay_only/C5"
    reference: "phi35_models_essay_only/C5"
  - name: "phi35_models_full_context/C1"
    reference: "phi35_models_full_context/C1"
  - name: "phi35_models_full_context/C2"
    reference: "phi35_models_full_context/C2"
  - name: "phi35_models_full_context/C3"
    reference: "phi35_models_full_context/C3"
  - name: "phi35_models_full_context/C4"
    reference: "phi35_models_full_context/C4"
  - name: "phi35_models_full_context/C5"
    reference: "phi35_models_full_context/C5"
  - name: "llama8_models_essay_only/C1"
    reference: "llama8_models_essay_only/C1"
  - name: "llama8_models_essay_only/C2"
    reference: "llama8_models_essay_only/C2"
  - name: "llama8_models_essay_only/C3"
    reference: "llama8_models_essay_only/C3"
  - name: "llama8_models_essay_only/C4"
    reference: "llama8_models_essay_only/C4"
  - name: "llama8_models_essay_only/C5"
    reference: "llama8_models_essay_only/C5"
  - name: "llama8_models_full_context/C1"
    reference: "llama8_models_full_context/C1"
  - name: "llama8_models_full_context/C2"
    reference: "llama8_models_full_context/C2"
  - name: "llama8_models_full_context/C3"
    reference: "llama8_models_full_context/C3"
  - name: "llama8_models_full_context/C4"
    reference: "llama8_models_full_context/C4"
  - name: "llama8_models_full_context/C5"
    reference: "llama8_models_full_context/C5"
  - name: "phi4_models_essay_only/C1"
    reference: "phi4_models_essay_only/C1"
  - name: "phi4_models_essay_only/C2"
    reference: "phi4_models_essay_only/C2"
  - name: "phi4_models_essay_only/C3"
    reference: "phi4_models_essay_only/C3"
  - name: "phi4_models_essay_only/C4"
    reference: "phi4_models_essay_only/C4"
  - name: "phi4_models_essay_only/C5"
    reference: "phi4_models_essay_only/C5"
  - name: "phi4_models_full_context/C1"
    reference: "phi4_models_full_context/C1"
  - name: "phi4_models_full_context/C2"
    reference: "phi4_models_full_context/C2"
  - name: "phi4_models_full_context/C3"
    reference: "phi4_models_full_context/C3"
  - name: "phi4_models_full_context/C4"
    reference: "phi4_models_full_context/C4"
  - name: "phi4_models_full_context/C5"
    reference: "phi4_models_full_context/C5"