# Configuration for running inference experiments sequentially
# Use this with --mode inference or --mode train

stop_on_failure: false
delay_between_experiments: 0

experiments:
  # Example: Run experiments with different models for each grade
  - name: "gervasio/C1"
    reference: "slm_decoder_models/C1"
  - name: "gervasio/C2"
    reference: "slm_decoder_models/C2"
  - name: "gervasio/C3"
    reference: "slm_decoder_models/C3"
  - name: "gervasio/C4"
    reference: "slm_decoder_models/C4"
  - name: "gervasio/C5"
    reference: "slm_decoder_models/C5"