# Configuration for running inference experiments sequentially
# Use this with --mode inference

stop_on_failure: true
delay_between_experiments: 0

experiments:
  # Example: Run inference with different models for each grade
  - name: "llama31-C1"
    reference: "slm_decoder_models/C1"
  
  - name: "llama31-C2"
    reference: "slm_decoder_models/C2"

  - name: "llama31-C3"
    reference: "slm_decoder_models/C3"
  
  - name: "llama31-C4"
    reference: "slm_decoder_models/C4"

  - name: "llama31-C5"
    reference: "slm_decoder_models/C5"